spring:
  application:
    name: BookStoreApp
datasource:
  url: jdbc:h2:mem:bookstoredb
  driver-class-name: org.h2.Driver
  username: admin
  password: admin
  platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

