name: Book Store APP Continuous Delivery

on:
  workflow_run:
    workflows:
      - Book Store APP Continuous Integration
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest
