name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build JAR
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*.jar
