name: Build and Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Build do projeto com Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Configuração do Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest .


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest
