name: Continuous Integration
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  build:
    name: Book Store Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build JAR
        run: ./gradlew build
      - name: List build output
        run: ls -R
      - name: Debug artifact paths
        run: find . -name "*.jar"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  docker:
    name: Send To Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest -f docker/Dockerfile .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore-app:latest